spring:
  application:
    name: bestshoes-api
  datasource:
    url: jdbc:postgresql://localhost:5432/bestshoes
    password: Password@1234
    username: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 min
    refreshTokenExpiration: 604800 # 1 week
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG